# Generated by Django 4.2 on 2023-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videospagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospage',
            name='language',
            field=models.CharField(default='English', max_length=250),
        ),
    ]
