# Generated by Django 4.2 on 2023-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videospage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospage',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
