# Generated by Django 4.1.7 on 2023-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customindexpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
