# Generated by Django 4.2 on 2023-06-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamespage_date'),
        ('snapshots', '0002_alter_snapshotspage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotspage',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='games.gamespage'),
        ),
    ]
