# Generated by Django 4.2 on 2023-06-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_snapshotspage_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotspage',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='snapshotspage',
            name='patreons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='snapshotspage',
            name='state',
            field=models.CharField(choices=[('option1', 'Draft'), ('option2', 'Public')], default='option1', max_length=20),
        ),
    ]
