# Generated by Django 4.2 on 2023-06-14 18:47

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_deckspage_date'),
        ('snapshots', '0005_snapshotspage_tierone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotspage',
            name='tierone',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select multiple Decks for this Snapshot', related_name='snapshots', to='decks.deckspage'),
        ),
    ]
