# Generated by Django 4.2 on 2023-06-14 19:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_deckspage_date'),
        ('snapshots', '0006_alter_snapshotspage_tierone'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotspage',
            name='tierhonorable',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select multiple Decks for this Snapshot', related_name='snapshots_tierhonorable', to='decks.deckspage'),
        ),
        migrations.AddField(
            model_name='snapshotspage',
            name='tierthree',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select multiple Decks for this Snapshot', related_name='snapshots_tierthree', to='decks.deckspage'),
        ),
        migrations.AddField(
            model_name='snapshotspage',
            name='tiertwo',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select multiple Decks for this Snapshot', related_name='snapshots_tiertwo', to='decks.deckspage'),
        ),
        migrations.AlterField(
            model_name='snapshotspage',
            name='tierone',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select multiple Decks for this Snapshot', related_name='snapshots_tierone', to='decks.deckspage'),
        ),
    ]
