# Generated by Django 4.2 on 2023-06-10 19:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_blogcategory_blogpage_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Post date')),
                ('image', models.ImageField(upload_to='sliders')),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogpage')),
            ],
        ),
    ]
