# Generated by Django 4.2 on 2023-06-10 20:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('blog', '0006_blogcategory_blogpage_categories'),
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('image', models.ImageField(upload_to='sliders')),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='SlidesModel',
        ),
    ]
