# Generated by Django 4.2 on 2023-06-10 21:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_slidespage_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidespage',
            name='secondtext',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
