# Generated by Django 4.2 on 2023-06-11 09:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_slidespage_secondtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidespage',
            name='thirdtext',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
