# Generated by Django 4.2 on 2023-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_slidespage_thirdtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidespage',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
