# Generated by Django 4.2 on 2023-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_deckspage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckspage',
            name='stars',
            field=models.FloatField(default=3),
        ),
    ]
