# Generated by Django 4.2 on 2023-06-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0002_rename_streamerpage_streamerspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamerspage',
            old_name='country',
            new_name='language',
        ),
    ]
