# Generated by Django 4.2 on 2023-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0004_streamerspage_instagramlink_streamerspage_tiktoklink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerspage',
            name='InstagramName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='streamerspage',
            name='TiktokName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='streamerspage',
            name='TwitchName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='streamerspage',
            name='TwitterName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='streamerspage',
            name='YoutubeName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
