# Generated by Django 4.1.3 on 2022-11-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
