# Generated by Django 4.1.3 on 2022-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_post_publish_date_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='https://www.youtube.com/watch?v=12SFwsHUjJs', max_length=200),
            preserve_default=False,
        ),
    ]
