# Generated by Django 4.1.3 on 2023-01-01 12:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_delete_tag_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('logo', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('link_to_website', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_twitch', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_discord', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
            ],
        ),
    ]
