# Generated by Django 4.1.3 on 2023-01-01 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_game_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ranking', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.snapshot')),
            ],
        ),
    ]
