# Generated by Django 4.1.3 on 2023-01-01 15:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_deckentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
            ],
        ),
        migrations.CreateModel(
            name='CardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('provision', models.IntegerField()),
                ('power', models.IntegerField()),
                ('game_version', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
            ],
        ),
    ]
