# Generated by Django 4.1.3 on 2023-01-01 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_card_deck_cardversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('link_to_website', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_twitch', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_discord', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('players_limit', models.IntegerField()),
                ('logo', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('playerA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerA', to='hub.player')),
                ('playerB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerB', to='hub.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.tournament')),
            ],
        ),
    ]
