# Generated by Django 4.1.3 on 2023-01-01 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_player_team_tournament_playertournamententry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('link_to_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_twitch', models.CharField(blank=True, max_length=200, null=True)),
                ('link_to_discord', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('howlong', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.platform')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.streamer')),
            ],
        ),
    ]
