# Generated by Django 4.2 on 2023-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulespage',
            name='timezone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
