# Generated by Django 4.2 on 2023-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedulespage_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulespage',
            name='hourFriday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourMonday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourSaturday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourSunday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourThursday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourTuesday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='hourWednesday',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isFriday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isMonday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isSaturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isSunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isThursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isTuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulespage',
            name='isWednesday',
            field=models.BooleanField(default=False),
        ),
    ]
