# Generated by Django 4.2 on 2023-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedulespage_hourfriday_schedulespage_hourmonday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulespage',
            name='hourFriday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourMonday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourSaturday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourSunday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourThursday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourTuesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedulespage',
            name='hourWednesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
