# Generated by Django 4.2 on 2023-06-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedulespage_streamer_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulespage',
            old_name='streamer_class',
            new_name='streamer',
        ),
    ]
